version: '3.8'

services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=easyorder
      - POSTGRES_USER=easyorder
      - POSTGRES_PASSWORD=easyorder
    ports:
      - "5432:5432"


  redis:
    image: redis:7.0.5
    ports:
      - "6379:6379"

  web:
    build: ./easyorder
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - ./easyorder/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - POSTGRES_NAME=easyorder
      - POSTGRES_USER=easyorder
      - POSTGRES_PASSWORD=easyorder
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
