# Generated by Django 3.2.19 on 2023-05-19 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import panel.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('exclude_ingredients', models.JSONField(blank=True, default=list, max_length=200, null=True)),
            ],
            options={
                'db_table': 'additional_order',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('main_address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('qr', models.ImageField(blank=True, null=True, upload_to=panel.models.qr_directory_path)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('icon', models.CharField(max_length=15)),
                ('default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='panel.brand')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('ingredients', models.CharField(blank=True, default='', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=panel.models.dishes_directory_path)),
                ('tags', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dishes', to='panel.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dishes', to='panel.category')),
            ],
            options={
                'db_table': 'dish',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('token', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.brand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed_at', models.DateTimeField()),
                ('order_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('ws_code', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('order_collection_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='panel.brand')),
                ('dishes', models.ManyToManyField(related_name='orders', through='panel.AdditionalOrder', to='panel.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='additionalorder',
            name='dish',
            field=models.ForeignKey(db_column='dish', on_delete=django.db.models.deletion.CASCADE, related_name='quantitats', to='panel.dish'),
        ),
        migrations.AddField(
            model_name='additionalorder',
            name='order',
            field=models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.CASCADE, related_name='quantitats', to='panel.order'),
        ),
        migrations.AlterUniqueTogether(
            name='additionalorder',
            unique_together={('order', 'dish')},
        ),
    ]
