# Generated by Django 3.2.19 on 2023-05-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
