# Generated by Django 3.2.19 on 2023-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ws_code',
            field=models.CharField(max_length=50),
        ),
    ]
