# Generated by Django 3.2.16 on 2022-12-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20221213_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
