# Generated by Django 3.2.19 on 2023-05-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20230520_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalorder',
            unique_together=set(),
        ),
    ]
