# Generated by Django 3.2.16 on 2023-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20221214_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed_at', models.DateTimeField()),
                ('order_delivered_at', models.DateTimeField()),
                ('ws_code', models.CharField(max_length=50)),
                ('dishes', models.ManyToManyField(to='panel.Dish')),
            ],
        ),
    ]
