# Generated by Django 3.2.19 on 2023-06-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_category_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
