# Generated by Django 3.2.19 on 2023-06-01 09:54

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_dish_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='', upload_to=panel.models.dishes_directory_path),
            preserve_default=False,
        ),
    ]
