# Generated by Django 3.2.16 on 2023-01-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_collection_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_placed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ws_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
