# Generated by Django 3.2.18 on 2023-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
