# Generated by Django 3.2.19 on 2023-05-08 16:34

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_brand_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to=panel.models.qr_directory_path),
        ),
    ]
