ORDER_PLACED = 0
ORDER_ACCEPTED = 1
ORDER_PREPARING = 2
ORDER_PREPARED = 3
ORDER_DELIVERED = 4

ORDER_CHOICES = (
    (ORDER_PLACED, 0),
    (ORDER_ACCEPTED, 1),
    (ORDER_PREPARING, 2),
    (ORDER_PREPARED, 3),
    (ORDER_DELIVERED, 4),
)
